theme: minima
title: Grumpy Hippo's personal blog
description: This is where I share cool stuff about my life
author: Grumpy Hippo

# GitHub Pages project site — change if you use a fork or custom domain
url: "https://ning-tan.github.io"
baseurl: "/grumpyhippo"
